from django.shortcuts import render


def profile_detail(request, username):
    """
    Render a user's profile page based on test data
    """
    context = {}
    # Test data uses the javascript-style true/false whereas we need the python-style True/False
    # When projects will be stored in the database, Django will automatically fix this for us
    false = False
    true = True
    # Mostly the same as homepage
    context["shared"] = [
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 1", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 1},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 2", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 2},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 3", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 3},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 4", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 4},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 5", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 5},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 6", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 6},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 7", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 7},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 8", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 8},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 9", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 9},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 10", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 10},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 11", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 11},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 12", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 12},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 13", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 13},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 14", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 14},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 15", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 15},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 16", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 16},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 17", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 17},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 18", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 18},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 19", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 19},
        {"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 20", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 20},
    ]
    context["favorites"] = context["shared"]
    context["followings"] = [
        {"fields": {"username": "test1", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 1},
        {"fields": {"username": "test2", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 2},
        {"fields": {"username": "test3", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 3},
        {"fields": {"username": "test4", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 4},
        {"fields": {"username": "test5", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 5},
        {"fields": {"username": "test6", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 6},
        {"fields": {"username": "test7", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 7},
        {"fields": {"username": "test8", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 8},
        {"fields": {"username": "test9", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 9},
        {"fields": {"username": "test10", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 10},
        {"fields": {"username": "test11", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 11},
        {"fields": {"username": "test12", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 12},
        {"fields": {"username": "test13", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 13},
        {"fields": {"username": "test14", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 14},
        {"fields": {"username": "test15", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 15},
        {"fields": {"username": "test16", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 16},
        {"fields": {"username": "test17", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 17},
        {"fields": {"username": "test18", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 18},
        {"fields": {"username": "test19", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 19},
        {"fields": {"username": "test20", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/user/default_60x60.png", "admin": false, "datetime_joined": "2001-09-11T10:03:00", "bio": "I am a test profile hard-coded into this website. I do not really exist.", "country": "Far Far Away", "status": "Testing this website."}, "model": "userprofiles.userprofile", "pk": 20},
    ]
    context["followers"] = context["followings"]
    context["galleriesfollowings"] = [
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 1", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 1},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 2", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 2},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 3", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 3},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 4", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 4},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 5", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 5},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 6", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 6},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 7", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 7},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 8", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 8},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 9", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 9},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 10", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 10},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 11", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 11},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 12", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 12},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 13", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 13},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 14", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 14},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 15", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 15},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 16", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 16},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 17", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 17},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 18", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 18},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 19", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 19},
        {"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 20", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 20},
    ]
    context["galleriescurating"] = context["galleriesfollowings"]
    return render(request, "profiles/profile_detail.html", context)


def scratcher_promotion_modal(request):
    return render(request, "profiles/scratcher_promotion_modal.html")
